name:                jungo-scripts
version:             0.1.0.0
github:              "jungoai/jungo-scripts"
author:              "Mohsen Nezamolmolki"
maintainer:          "thelight.mn@gmail.com"

extra-source-files:
  - README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/jungo-startup#readme>

dependencies:
  - base >= 4.7 && < 5
  - turtle == 1.6.2
  - yaml
  - aeson == 2.2.3.0
  - text

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

executables:
  jungochain-run:
    main:                JungochainRun.hs
    source-dirs:         scripts
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    default-extensions:
      - OverloadedStrings
      - DeriveGeneric
      - DeriveAnyClass
