name: Build Haskell via devShell

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Cache Cabal
      uses: actions/cache@v4
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal', 'cabal.project') }}

    - name: Build with cabal in nix develop
      run: |
        nix develop --command bash -c "cabal update && cabal build all"
